week8: week8.tex
	pdflatex week8.tex && open week8.pdf

week6: week6.tex
	pdflatex week6.tex && open week6.pdf

week5: week5.tex
	pdflatex week5.tex && open week5.pdf

week4: week4.tex
	pdflatex week4.tex && open week4.pdf

week3: week3.tex
	pdflatex week3.tex && open week3.pdf

week2: week2.tex
	pdflatex week2.tex && open week2.pdf

hw5: hw5.tex
	pdflatex hw5.tex && open hw5.pdf

hw4: hw4.tex
	pdflatex hw4.tex && open hw4.pdf

hw3: hw3.tex
	pdflatex hw3.tex && open hw3.pdf

hw2: hw2.tex
	pdflatex hw2.tex && open hw2.pdf

hw1: hw1.tex
	pdflatex hw1.tex && open hw1.pdf

clean:
	rm -rf *.out *.aux *.log
